import UserSvg from "./UserSvg";
import MessageSvg from "./MessageSvg";
import SettingSvg from "./SettingSvg";
import SendSvg from "./SendSvg";
import AddSvg from "./AddSvg";
import ChatSvg from "./ChatSvg";
import AcceptSvg from "./AcceptSvg";
import AddUserSvg from "./AddUserSvg";
import PendingSvg from "./PendingSvg";
export { UserSvg, MessageSvg, SettingSvg, SendSvg, AddSvg, ChatSvg, AcceptSvg, AddUserSvg, PendingSvg };
